### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by amrography** [foamliu/Car-Recognition#19]
Hello,

I followed the installed instructions then when I run `python train.py` I am getting this error

```
$ python train.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import keras
  File "/Library/Python/2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Library/Python/2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Library/Python/2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/Library/Python/2.7/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/Library/Python/2.7/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/Library/Python/2.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

I also get the same exact error when running `python analyze.py` or `python demo.py`

**Comment by foamliu** [comment]
The error happens during keras import, and that means it has nothing to do with this project. Please make sure tensorflow anda keras are installed successfully.

**Comment by amrography** [comment]
@foamliu thanks for quick respond I ran `pip install tensorflow keras --ignore-installed` and installed many packages. Thanks for your great effort!

**Comment by amrography** [comment]
@foamliu  Can you please list the modules version.

I have `tensorflow 2.1.0` which requires `scipy < 1.2.2`
and `keras 2.3` which requires `scipy > 1.2.3`

but `keras 2.3` needs `tensorflow > 2.0`
