### ISSUE TITLE
Typo in analyze.py

### ISSUE THREAD

**Issue by JamesMDe** [foamliu/Car-Recognition#22]
Hello, 

A coworker and I were trying to run analyze.py and received the following error:

Traceback (most recent call last):
  File "analyze.py", line 106, in <module>
    y_pred, y_test = predict('data/valid', model)
  File "analyze.py", line 44, in predict
    class_id = int(tokens[-2])
IndexError: list index out of range 

It appears that os.pathsep that is passed into the split function on line 44 in analyze.py is delimiting using a ':' instead of a '/'. Passing in os.path.sep instead fixed the problem!

**Comment by Usman-Ghani123** [comment]
Use this instead of the one in the code it will solve the problem. 
tokens=img_path.split('\\')
