### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by sygnz** [foamliu/Car-Recognition#4]
Hello foamliu,

I am getting error. I edited my model's path, weights of it. But the error is below;

Load the trained ResNet model....
2019-03-04 01:34:55.733266: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "analyze.py", line 107, in <module>
    y_pred, y_test = predict('data/valid', model)
  File "analyze.py", line 43, in predict
    class_id = int(tokens[-2])
ValueError: invalid literal for int() with base 10: 'data'

Cause of both 2 variables are different. Can you organize the code again? Or what's my problem now?

Thanks.

PS: Python 3.5.2, Tensorbard 1.12.2, Keras 2.2.4, updated the others.

**Comment by sygnz** [comment]
Sorry, i haven't seen a "1 pull request". i am trying this and working. Wait for it. :)

**Comment by sygnz** [comment]
Finished. Now i'm testing. Sorry. ;)
